#!/usr/bin/env node
import { mkdir, readFile, writeFile, readdir, unlink } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { repoRoot, parseArgs } from './lib/util.mjs'

const ROOT = repoRoot()
const MANIFEST_PATH = join(ROOT, 'skills', 'skills.json')
const CLAUDE_COMMANDS_DIR = join(ROOT, '.claude', 'commands')

const GENERATED_MARKER = '<!-- generated-by: scripts/install-skills.mjs -->'

function delegateBody(skill, agentDoc) {
  const args = skill.argumentHint
    ? `\nargument-hint: ${skill.argumentHint}`
    : ''
  return `---
description: ${skill.description}${args}
---

${GENERATED_MARKER}

# /${skill.name}

Follow the **"${skill.section}"** section in \`${agentDoc}\` at the project
root. It contains the canonical workflow for this skill.

If the user supplied \`$ARGUMENTS\`, treat it as initial context (topic,
brief, or a path to a source file) and skip directly to confirming the
remaining inputs.

Read \`${agentDoc}\` now if you haven't already this session, then proceed.
`
}

async function readManifest() {
  if (!existsSync(MANIFEST_PATH)) {
    throw new Error(`skills/skills.json not found at ${MANIFEST_PATH}`)
  }
  const raw = await readFile(MANIFEST_PATH, 'utf-8')
  const parsed = JSON.parse(raw)
  if (!Array.isArray(parsed.skills)) {
    throw new Error('skills.json must contain a "skills" array')
  }
  if (!parsed.agentDoc) parsed.agentDoc = 'AGENTS.md'
  return parsed
}

async function readAgentSections(agentDoc) {
  const path = join(ROOT, agentDoc)
  if (!existsSync(path)) {
    throw new Error(`Agent doc not found: ${agentDoc}`)
  }
  const text = await readFile(path, 'utf-8')
  const headings = new Set()
  for (const line of text.split('\n')) {
    const m = line.match(/^##\s+(.+?)\s*$/)
    if (m) headings.add(m[1])
  }
  return headings
}

function validate(manifest, sections) {
  const errors = []
  const seen = new Set()
  for (const skill of manifest.skills) {
    if (!skill.name) {
      errors.push('skill missing "name"')
      continue
    }
    if (!/^[a-z0-9][a-z0-9-]*$/.test(skill.name)) {
      errors.push(
        `skill "${skill.name}" — name must be kebab-case [a-z0-9-]`
      )
    }
    if (seen.has(skill.name)) errors.push(`duplicate skill name: ${skill.name}`)
    seen.add(skill.name)
    if (!skill.description) errors.push(`skill "${skill.name}" missing "description"`)
    if (!skill.section) errors.push(`skill "${skill.name}" missing "section"`)
    else if (!sections.has(skill.section)) {
      errors.push(
        `skill "${skill.name}" — section "${skill.section}" not found as an H2 in ${manifest.agentDoc}`
      )
    }
  }
  return errors
}

async function cleanStaleDelegates(activeNames) {
  if (!existsSync(CLAUDE_COMMANDS_DIR)) return []
  const removed = []
  const entries = await readdir(CLAUDE_COMMANDS_DIR)
  for (const file of entries) {
    if (!file.endsWith('.md')) continue
    const name = file.replace(/\.md$/, '')
    if (activeNames.has(name)) continue
    const full = join(CLAUDE_COMMANDS_DIR, file)
    const content = await readFile(full, 'utf-8')
    if (content.includes(GENERATED_MARKER)) {
      await unlink(full)
      removed.push(file)
    }
  }
  return removed
}

async function main() {
  const { args } = parseArgs(process.argv.slice(2))
  const check = !!args.check
  const verbose = !!args.verbose

  const manifest = await readManifest()
  const sections = await readAgentSections(manifest.agentDoc)
  const errors = validate(manifest, sections)
  if (errors.length) {
    console.error('\n  ✗ Manifest validation failed:')
    for (const e of errors) console.error('     -', e)
    console.error('')
    process.exit(1)
  }

  const activeNames = new Set(manifest.skills.map((s) => s.name))
  await mkdir(CLAUDE_COMMANDS_DIR, { recursive: true })

  const writes = []
  for (const skill of manifest.skills) {
    const target = join(CLAUDE_COMMANDS_DIR, `${skill.name}.md`)
    const body = delegateBody(skill, manifest.agentDoc)
    const existing = existsSync(target) ? await readFile(target, 'utf-8') : null
    if (existing && !existing.includes(GENERATED_MARKER)) {
      console.error(
        `\n  ✗ ${target} exists and was not generated by this script.`
      )
      console.error(
        `     Refusing to overwrite a hand-edited file. Remove the file or add\n` +
          `     the marker line "${GENERATED_MARKER}" if you want this script to manage it.\n`
      )
      process.exit(1)
    }
    if (existing === body) {
      if (verbose) console.log(`  =  .claude/commands/${skill.name}.md  (unchanged)`)
      continue
    }
    if (check) {
      console.error(`  ✗ .claude/commands/${skill.name}.md is out of sync`)
      process.exit(1)
    }
    writes.push({ target, body, name: skill.name, isNew: !existing })
  }

  const removed = check
    ? []
    : await cleanStaleDelegates(activeNames)

  if (check && writes.length === 0 && removed.length === 0) {
    console.log('  ✓ All generated delegates are in sync.')
    return
  }

  for (const w of writes) {
    await writeFile(w.target, w.body, 'utf-8')
    console.log(`  ${w.isNew ? '+' : '~'}  .claude/commands/${w.name}.md`)
  }
  for (const r of removed) {
    console.log(`  -  .claude/commands/${r}`)
  }

  console.log('')
  console.log(`  ✓ Installed ${manifest.skills.length} skill${manifest.skills.length === 1 ? '' : 's'}.`)
  console.log('')
}

main().catch((err) => {
  console.error(`\n  ✗  ${err.message}\n`)
  process.exit(1)
})
